name: "CCF App Samples CI"
# Created based on https://github.com/microsoft/ccf-app-template

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:

  build-containers:
    runs-on: ubuntu-20.04
    container: mcr.microsoft.com/ccf/app/dev:lts-devcontainer

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build JS enclave container
        run: docker build -t ccf-app-template:js-enclave -f docker/ccf_app_js.enclave .

      - name: Build JS virtual container
        run: docker build -t ccf-app-template:js-virtual -f docker/ccf_app_js.virtual .

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: 16.0

      - name: Test Banking application
        run: |
          cd banking-app
          npm ci
          ./test.sh

