name: "CCF App Samples CI"
# Created based on https://github.com/microsoft/ccf-app-template

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  banking-app-sample:
    name: Banking app sample
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Build samples in DevContainer
        uses: devcontainers/ci@v0.2
        with:
          runCmd: |
            git config --global --add safe.directory "$GITHUB_WORKSPACE"
            make lint
            cd banking-app && make test && make test-docker-virtual
          env: |
            GITHUB_WORKSPACE

  auditable-logging-app-sample:
    name: Auditable logging app sample
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Build samples in DevContainer
        uses: devcontainers/ci@v0.2
        with:
          runCmd: |
            cd auditable-logging-app && make test
