name: "CCF App Samples CI"
# Created based on https://github.com/microsoft/ccf-app-template

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  banking-app-sample:
    name: Banking app sample
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Banking app sample
        uses: devcontainers/ci@v0.2
        with:
          imageName: ghcr.io/microsoft/ccf-samples-devcontainer
          cacheFrom: ghcr.io/microsoft/ccf-samples-devcontainer
          push: always
          runCmd: |
            git config --global --add safe.directory "$GITHUB_WORKSPACE"
            make lint
            cd banking-app && make test && make test-docker-virtual
          env: |
            GITHUB_WORKSPACE

      - name: Auditable logging app sample
        uses: devcontainers/ci@v0.2
        with:
          cacheFrom: ghcr.io/microsoft/ccf-samples-devcontainer
          push: never
          runCmd: |
            cd auditable-logging-app && make test && make test-docker-virtual

      - name: Data Reconciliation app sample
        uses: devcontainers/ci@v0.2
        with:
          cacheFrom: ghcr.io/microsoft/ccf-samples-devcontainer
          push: never
          runCmd: |
            cd data-reconciliation-app && make unit-test && make test && make test-docker-virtual && make e2e-test && make e2e-test-docker

  
