name: "CCF App Samples CI"
# Created based on https://github.com/microsoft/ccf-app-template

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  banking-app-sample:
    name: Banking app sample
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Build samples in DevContainer
        uses: devcontainers/ci@v0.3
        with:
          cacheFrom: ghcr.io/microsoft/ccf-samples-devcontainer
          runCmd: |
            git config --global --add safe.directory "$GITHUB_WORKSPACE"
            make lint
            cd banking-app && make test
          env: |
            GITHUB_WORKSPACE

  auditable-logging-app-sample:
    name: Auditable logging app sample
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Build samples in DevContainer
        uses: devcontainers/ci@v0.3
        with:
          cacheFrom: ghcr.io/microsoft/ccf-samples-devcontainer
          runCmd: |
            cd auditable-logging-app && make test

  data-reconciliation-app-sample:
    name: Data Reconciliation app sample
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Build samples in DevContainer
        uses: devcontainers/ci@v0.3
        with:
          cacheFrom: ghcr.io/microsoft/ccf-samples-devcontainer
          runCmd: |
            cd data-reconciliation-app && make unit-test && make test

  decentralized-rbac-app-sample:
    name: Decentralized RBAC app sample
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Build samples in DevContainer
        uses: devcontainers/ci@v0.3
        with:
          cacheFrom: ghcr.io/microsoft/ccf-samples-devcontainer
          runCmd: |
            cd decentralized-rbac-app && make test
