name: "CCF App Template CI"

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-cpp-app:
    runs-on: ubuntu-20.04
    container: mcr.microsoft.com/ccf/app/dev:lts-devcontainer

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build app
        run: mkdir -p build && cd build && CC="/opt/oe_lvi/clang-10" CXX="/opt/oe_lvi/clang++-10" cmake -GNinja .. && ninja
        working-directory: cpp

  build-containers:
    runs-on: ubuntu-20.04
    container: mcr.microsoft.com/ccf/app/dev:lts-devcontainer

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build C++ enclave container
        run: docker build -t ccf-app-template:cpp-enclave -f docker/ccf_app_cpp.enclave .

      - name: Build C++ virtual container
        run: docker build -t ccf-app-template:cpp-virtual -f docker/ccf_app_cpp.virtual .

      - name: Build JS enclave container
        run: docker build -t ccf-app-template:js-enclave -f docker/ccf_app_js.enclave .

      - name: Build JS virtual container
        run: docker build -t ccf-app-template:js-virtual -f docker/ccf_app_js.virtual .
